import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Weather App
        </h1>

        <p className={styles.description}>
         Get the weather for any city by inputting a city name below and pressing submit!
        </p>

        <div className={styles.grid}>
          <form onSubmit={submitLocation2}>
          <label for="city">City: </label>
          <input type="text" id="city" name="city"/>
          <button type="submit">Submit</button>
         </form> 

         
        </div>
      </main>
	

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

function submitLocation2(event) {
  alert(event.target.city.value);
  //const location = event.target.city.value;
  //const info = await fetch('http://api.openweathermap.org/geo/1.0/direct?q={location}&appid={a06f7c0500b6f20cb044d20ec3d49dc0}')
  //const information = await info.json();
  //const res = await fetch('https://api.openweathermap.org/data/2.5/weather?lat={info.lat}&lon={info.lon}&appid={a06f7c0500b6f20cb044d20ec3d49dc0}');
  //const result = await res.json();
  //alert(`The weather in ${city} is: ${result}`);
}
